// flow-typed signature: 724167c5cd183cb9cd350d1343c15bd2
// flow-typed version: <<STUB>>/jest-styled-components_v^1.3.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-styled-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-styled-components/src/index' {
  declare module.exports: any;
}

declare module 'jest-styled-components/src/matcher' {
  declare module.exports: any;
}

declare module 'jest-styled-components/src/serializer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-styled-components/src/index.js' {
  declare module.exports: $Exports<'jest-styled-components/src/index'>;
}
declare module 'jest-styled-components/src/matcher.js' {
  declare module.exports: $Exports<'jest-styled-components/src/matcher'>;
}
declare module 'jest-styled-components/src/serializer.js' {
  declare module.exports: $Exports<'jest-styled-components/src/serializer'>;
}
