/* @flow */
const PRIMARY = '#FFC92F';
const Primary = {
  LIGHTER: '#FFD459',
  LIGHT: '#FFCF45',
  DARK: '#FEC216',
  DARKER: '#FAB900',
};

const SECONDARY = '#FF7E36';
const Secondary = {
  LIGHTER: '#FF9358',
  LIGHT: '#FF8A4A',
  DARK: '#FA7429',
  DARKER: '#F1691D',
};

const BLACK_SUEDE_BEHR = '#3D3E3C';
const BLACK_BENJAMIN_MOORE = '#323233';
const EERIE_BLACK = '#1B1B1B';

const BLACK = BLACK_BENJAMIN_MOORE;
const Black = {
  LIGHT: BLACK_SUEDE_BEHR,
  MODERATE: BLACK_BENJAMIN_MOORE,
  STRONG: EERIE_BLACK,
  TRANSPARENT: 'rgba(50, 50, 51, 0.8)',
};

const NORMAL_WHITE = '#FFFFFF';
const SEETHA_WHITE = '#FCFCFA';
const COTTON_BALLS_BENJAMIN_MOORE = '#F6F7EC';

const WHITE = SEETHA_WHITE;
const White = {
  LIGHT: NORMAL_WHITE,
  MODERATE: SEETHA_WHITE,
  STRONG: COTTON_BALLS_BENJAMIN_MOORE,
  TRANSPARENT: 'rgba(255, 255, 255, 0.12)',
};

const ICE_CUBED_SILVER_BENJAMIN_MOORE = '#DDE2E2';
const SARONIA_GRAY = '#D2D7D9';
const GRAY_PINSTRIP_BENJAMIN_MOORE = '#798282';

const GRAY = SARONIA_GRAY;
const Gray = {
  LIGHT: ICE_CUBED_SILVER_BENJAMIN_MOORE,
  MODERATE: SARONIA_GRAY,
  STRONG: GRAY_PINSTRIP_BENJAMIN_MOORE,
};

const GREEK_VILLA_SHERWIN_WILLIAMS = '#F0ECE2';
const ALABASTER_SHERWIN_WILLIAMS = '#EDEAE0';
const MARITIME_WHITE_BENJAMIN_MOORE = '#E6DFCF';

const CREME = ALABASTER_SHERWIN_WILLIAMS;
const Creme = {
  LIGHT: GREEK_VILLA_SHERWIN_WILLIAMS,
  MODERATE: ALABASTER_SHERWIN_WILLIAMS,
  STRONG: MARITIME_WHITE_BENJAMIN_MOORE,
};

const Context = {
  DANGER: 'hsl(348, 100%, 61%)',
  SUCCESS: 'hsl(141, 71%,  48%)',
  WARNING: 'hsl(48, 100%, 67%)',
  INFO: 'hsl(217, 71%, 53%)',
};

export default {
  PRIMARY,
  Primary,
  SECONDARY,
  Secondary,
  BLACK,
  Black,
  WHITE,
  White,
  GRAY,
  Gray,
  CREME,
  Creme,
  Context,
};
