/* @flow */
const PRIMARY = '#FFCA33';
const Primary = {
  LIGHT: '#FFD14D',
  LIGHTER: '#FFD96C',
  DARK: '#FEC417',
  DARKER: '#FFBE00',
};

const SECONDARY = '#F26327';
const Secondary = {
  LIGHT: '#F26A31',
  LIGHTER: '#F3723C',
  DARK: '#F15919',
  DARKER: '#EE500E',
};

const BLACK_SUEDE_BEHR = '#3D3E3C';
const BLACK_BENJAMIN_MOORE = '#323233';
const BLACK_TRICORN_SHERWIN_WILLIAMS = '#2F2F30';

const BLACK = BLACK_BENJAMIN_MOORE;
const Black = {
  LIGHT: BLACK_SUEDE_BEHR,
  MODERATE: BLACK_BENJAMIN_MOORE,
  STRONG: BLACK_TRICORN_SHERWIN_WILLIAMS,
  TRANSPARENT: 'rgba(50, 50, 51, 0.8)',
};

const ALL_WHITE_FARROW_BALL = '#F7F6F2';
const PURE_WHITE_SHERWIN_WILLIAMS = '#EDECE6';
const PAPER_WHITE_BENJAMIN_MOORE = '#E1E3DD';

const WHITE = PURE_WHITE_SHERWIN_WILLIAMS;
const White = {
  LIGHT: ALL_WHITE_FARROW_BALL,
  MODERATE: PURE_WHITE_SHERWIN_WILLIAMS,
  STRONG: PAPER_WHITE_BENJAMIN_MOORE,
};

const GRAY_CLOUD_BENJAMIN_MOORE = '#D8DDDF';
const FEATHER_GRAY_BENJAMIN_MOORE = '#C5CCD1';
const PILGRIM_HAZE_BENJAMIN_MOORE = '#9FA8AE';

const GRAY = FEATHER_GRAY_BENJAMIN_MOORE;
const Gray = {
  LIGHT: GRAY_CLOUD_BENJAMIN_MOORE,
  MODERATE: FEATHER_GRAY_BENJAMIN_MOORE,
  STRONG: PILGRIM_HAZE_BENJAMIN_MOORE,
};

const ALABASTER_SHERWIN_WILLIAMS = '#EDEAE0';
const GREEK_VILLA_SHERWIN_WILLIAMS = '#F0ECE2';
const MARITIME_WHITE_BENJAMIN_MOORE = '#E6DFCF';

const CREME = ALABASTER_SHERWIN_WILLIAMS;
const Creme = {
  LIGHT: GREEK_VILLA_SHERWIN_WILLIAMS,
  MODERATE: ALABASTER_SHERWIN_WILLIAMS,
  STRONG: MARITIME_WHITE_BENJAMIN_MOORE,
};

const Context = {
  DANGER: 'hsl(348, 100%, 61%)',
  SUCCESS: 'hsl(141, 71%,  48%)',
  WARNING: 'hsl(48, 100%, 67%)',
  INFO: 'hsl(217, 71%, 53%)',
};

export default {
  PRIMARY,
  Primary,
  SECONDARY,
  Secondary,
  BLACK,
  Black,
  WHITE,
  White,
  GRAY,
  Gray,
  CREME,
  Creme,
  Context,
};
