FROM nginx:1.13.0-alpine
MAINTAINER Prasath Soosaithasan <prasath.soosaithasan@gmail.com>

# -------------------------------------------------------------------------
#  Bake static files into image
# -------------------------------------------------------------------------
COPY dist-storybook /usr/share/nginx/html
